// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXJbfjL02MFiTRDSWq5o_VkeHn36n6_v4',
    appId: '1:103429393553:web:40458f0063077c9abf0330',
    messagingSenderId: '103429393553',
    projectId: 'lista-de-contatos-584c4',
    authDomain: 'lista-de-contatos-584c4.firebaseapp.com',
    storageBucket: 'lista-de-contatos-584c4.appspot.com',
    measurementId: 'G-X340T3BR2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv8AfmHdCQZzNOIj19YKooWhm6ryrajf4',
    appId: '1:103429393553:android:df4a7fb2e41e2bb3bf0330',
    messagingSenderId: '103429393553',
    projectId: 'lista-de-contatos-584c4',
    storageBucket: 'lista-de-contatos-584c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY_zv8Q6P8MolrxiZ4T_rHtkXZFNs5UIs',
    appId: '1:103429393553:ios:c3f00c93639c7522bf0330',
    messagingSenderId: '103429393553',
    projectId: 'lista-de-contatos-584c4',
    storageBucket: 'lista-de-contatos-584c4.appspot.com',
    iosBundleId: 'com.brunocardozo.listaDeConversa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY_zv8Q6P8MolrxiZ4T_rHtkXZFNs5UIs',
    appId: '1:103429393553:ios:c3f00c93639c7522bf0330',
    messagingSenderId: '103429393553',
    projectId: 'lista-de-contatos-584c4',
    storageBucket: 'lista-de-contatos-584c4.appspot.com',
    iosBundleId: 'com.brunocardozo.listaDeConversa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXJbfjL02MFiTRDSWq5o_VkeHn36n6_v4',
    appId: '1:103429393553:web:ba6db24c35d4763dbf0330',
    messagingSenderId: '103429393553',
    projectId: 'lista-de-contatos-584c4',
    authDomain: 'lista-de-contatos-584c4.firebaseapp.com',
    storageBucket: 'lista-de-contatos-584c4.appspot.com',
    measurementId: 'G-7BZ41Z6NSL',
  );

}